apiVersion : apps/v1
kind: Deployment
metadata:
  name: movieapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp 
    spec:
      containers:
        - name: movieapp 
          image: devopslearnacrmohan.azurecr.io/movieapp
          ports:
          - containerPort: 80/tcp